apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: andrea-dimaio-buildah-assignment
spec:
  workspaces:
    - name: buildah-assignment-shared-data
  tasks:
  - name: clone-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: https://github.com/cloud-native-garage-method-cohort/andrea-dimaio-buildah-assignment
    workspaces:
    - name: output
      workspace: buildah-assignment-shared-data
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
      - name: IMAGE
        value: quay.io/andrea-dimaio-it/bootcamp
    workspaces:
      - name: source
        workspace: buildah-assignment-shared-data
    runAfter: 
      - clone-repository
  - name: kustomize-build
    runAfter:
       - build-image
    params:
       - name: app-namespace
         value: andrea-dimaio-pipeline-from-scratch
       - name: app-name
         value: express-app
       - name: image-with-tag
         value: "quay.io/andrea-dimaio-it/bootcamp:$(tasks.clone-repository.results.commit)"
    taskRef:
       kind: Task
       name: kustomize-build
    workspaces:
       - name: source
         workspace: buildah-assignment-shared-data
